<channels>
<channel>
<name>[COLOR white]LANÇAMENTOS[/COLOR]</name>
<thumbnail>https://ia801400.us.archive.org/12/items/desenhos_201909/John.png</thumbnail>
<externallink>https://raw.githubusercontent.com/arifelcris/ADDON-ELETRONICA/master/MENU%2004%20FILMES%20LAN%C3%87AMENTOS</externallink>
<fanart>https://ia801400.us.archive.org/12/items/desenhos_201909/fime%20vingadores.png</fanart>
<info>


[COLOR deeppink]|[/COLOR]- OS MELHORES LANÇAMENTOS -[COLOR deeppink]|[/COLOR]</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<channels>
<channel>
<name>[COLOR white]AÇÃO[/COLOR]</name>
<thumbnail>https://ia601404.us.archive.org/31/items/faroeste/a%C3%A7ao.png</thumbnail>
<externallink>https://raw.</externallink>
<fanart>https://ia601404.us.archive.org/31/items/faroeste/a%C3%A7ao%20todos.png</fanart>
<info>


[COLOR deeppink]|[/COLOR]- OS MELHORES FILMES DE AÇÃO -[COLOR deeppink]|[/COLOR]</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<channels>
<channel>
<name>[COLOR white]COMÉDIA[/COLOR]</name>
<thumbnail>https://ia801404.us.archive.org/31/items/faroeste/mr%20bin.png</thumbnail>
<externallink>https://raw.</externallink>
<fanart>https://ia801404.us.archive.org/31/items/faroeste/comediantes.png</fanart>
<info>


[COLOR deeppink]|[/COLOR]- OS MELHORES FILMES DE COMÉDIA -[COLOR deeppink]|[/COLOR]</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<channels>
<channel>
<name>[COLOR white]FAROESTE[/COLOR]</name>
<thumbnail>https://archive.org/download/faroeste/faroeste.png</thumbnail>
<externallink>https://raw.</externallink>
<fanart>https://ia801404.us.archive.org/31/items/faroeste/fundo%20faroeste.png</fanart>
<info>


[COLOR deeppink]|[/COLOR]- OS MELHORES FILMES DE FAROESTES NOVOS E ANTIGOS -[COLOR deeppink]|[/COLOR]</info>
</channel>
</channels>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
